volumes:
  key_value_local_postgres_data: {}
  key_value_local_postgres_data_backups: {}
  redis-data:


services:
  postgres:
    image: postgres:16
    container_name: key_value_local_postgres
    ports:
      - 5432:5432
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - key_value_local_postgres_data:/var/lib/postgresql/data
      - key_value_local_postgres_data_backups:/backups

  redis:
    image: redis:7
    container_name: key_value_local_redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
